#!/bin/bash
source $1
cd $2
pip install -r requirements.txt
python setup.py build --force
python setup.py install
python setup.py clean
deactivate
cd /mnt/c/Users/MichelEbner/Development/WeAreDevelopers/Nasa_example
